version: "3"

services:
  mocks:
    build:
      context: ./mocks
      dockerfile: dockerfile
    ports:
      - 8080:8080
  # app:
  #   build:
  #     context: ./
  #     dockerfile: dockerfile
  #   ports:
  #     - 3000:3000